// eslint-disable-next-line @typescript-eslint/no-var-requires
const bwipjs = require('bwip-js');

export interface BarcodeQualityResult {
  ok: boolean;
  warning?: string;
  nativeWidthPx: number;
  nativeHeightPx: number;
  estimatedModuleWidthMm: number;
  estimatedPhysicalWidthMm: number;
  estimatedPhysicalHeightMm: number;
}

/** Reads width/height directly from a PNG's IHDR chunk instead of
 * guessing from input parameters — bwip-js's actual output size
 * depends on the encoded text length in a way that's easy to get
 * subtly wrong by calculation alone, and this bug class (barcode
 * "prints" but isn't scannable) is exactly the kind of thing that
 * should be verified against the real generated bytes, not assumed. */
function readPngDimensions(png: Buffer): { width: number; height: number } {
  return {
    width: png.readUInt32BE(16),
    height: png.readUInt32BE(20),
  };
}

// Widely-used minimum reliable module width for retail laser/CCD
// scanners at typical scan distance. Going narrower than this is the
// single most common cause of "prints fine, won't scan."
const MIN_MODULE_WIDTH_MM = 0.25;
// Target DPI to design for — covers both common cheap thermal
// printers (203dpi) and higher-end ones (300dpi) with margin, so the
// source image never needs the printer itself to upscale it.
const TARGET_DPI = 300;
const PX_PER_MM = TARGET_DPI / 25.4;

export type ScannableBarcodeFormat = 'code128' | 'ean13' | 'ean8' | 'upca' | 'qrcode';

/**
 * Real per-format module-count math. CODE128 is variable-length
 * (~11 modules/char + ~35 overhead), but EAN13/EAN8/UPC-A are FIXED-
 * structure symbologies — every valid EAN13 has exactly 95 modules
 * (the standard demands it; that's how scanners recognize the format
 * at all). Reusing CODE128's variable-length formula for these would
 * have silently produced the wrong target scale for every single one.
 */
function estimatedModuleCount(format: ScannableBarcodeFormat, text: string): number {
  switch (format) {
    case 'ean13': return 95;
    case 'ean8': return 67;
    case 'upca': return 95;
    case 'qrcode': return 0; // QR sizing isn't modules-in-a-row; handled separately below
    default: return 35 + String(text || '1').length * 11;
  }
}

/**
 * Generates a retail-scannable barcode (or QR code) sized for real
 * scannability — not a fixed `scale` that happens to work for some
 * text lengths/formats and not others. Returns the real measured
 * native pixel dimensions so the caller can set <img> width/height to
 * match 1:1 (no CSS stretching, no blur from interpolation) and a
 * quality verdict so a too-small result can surface a warning instead
 * of silently shipping an unscannable label.
 */
export async function generateScannableBarcode(
  text: string,
  opts?: { targetWidthMm?: number; targetHeightMm?: number; format?: ScannableBarcodeFormat; eccLevel?: 'M' | 'Q' },
): Promise<{ dataUri: string; widthPx: number; heightPx: number; quality: BarcodeQualityResult }> {
  const format = opts?.format || 'code128';
  const targetWidthMm = opts?.targetWidthMm ?? 38;
  const targetHeightMm = opts?.targetHeightMm ?? 16;
  const targetWidthPx = Math.round(targetWidthMm * PX_PER_MM);
  const targetHeightPx = Math.round(targetHeightMm * PX_PER_MM);

  if (format === 'qrcode') {
    // QR sizing is per-side, not module-width — a fixed minimum scale
    // is the right approach here (QR error correction handles the
    // rest), but it must still be sized to the real target, not a
    // single number reused for every label size.
    const targetSidePx = Math.min(targetWidthPx, targetHeightPx > 0 ? targetHeightPx : targetWidthPx);
    let qrScale = Math.max(3, Math.round(targetSidePx / 25));
    let qrPng = await bwipjs.toBuffer({ bcid: 'qrcode', text: text || 'N/A', scale: qrScale, eclevel: opts?.eccLevel || 'M' });
    let qrDims = readPngDimensions(qrPng);
    const qrPhysicalSizeMm = qrDims.width / PX_PER_MM;
    const quality: BarcodeQualityResult = {
      ok: qrPhysicalSizeMm >= 15,
      nativeWidthPx: qrDims.width,
      nativeHeightPx: qrDims.height,
      estimatedModuleWidthMm: 0,
      estimatedPhysicalWidthMm: Math.round(qrPhysicalSizeMm * 10) / 10,
      estimatedPhysicalHeightMm: Math.round((qrDims.height / PX_PER_MM) * 10) / 10,
    };
    if (!quality.ok) quality.warning = `QR code is only ${quality.estimatedPhysicalWidthMm}mm — recommended minimum 15mm per side for reliable phone-camera scanning.`;
    return { dataUri: `data:image/png;base64,${qrPng.toString('base64')}`, widthPx: qrDims.width, heightPx: qrDims.height, quality };
  }

  const estimatedModules = estimatedModuleCount(format, text);
  let scale = Math.max(2, Math.ceil(targetWidthPx / estimatedModules));
  const heightUnits = Math.max(10, Math.round(targetHeightPx / scale));

  let png: Buffer;
  let dims: { width: number; height: number };
  let attempts = 0;
  do {
    // eslint-disable-next-line no-await-in-loop
    png = await bwipjs.toBuffer({
      bcid: format,
      text: text || 'N/A',
      scale,
      height: heightUnits,
      includetext: false,
    });
    dims = readPngDimensions(png);
    attempts++;
    if (dims.width >= targetWidthPx * 0.9) break;
    scale += 1; // narrower than expected (can happen for very short text) — try a higher scale
  } while (attempts < 4);

  const estimatedModuleWidthMm = (dims.width / estimatedModules) / PX_PER_MM;
  const estimatedPhysicalWidthMm = dims.width / PX_PER_MM;
  const estimatedPhysicalHeightMm = dims.height / PX_PER_MM;

  const quality: BarcodeQualityResult = {
    ok: estimatedModuleWidthMm >= MIN_MODULE_WIDTH_MM && estimatedPhysicalHeightMm >= 15,
    nativeWidthPx: dims.width,
    nativeHeightPx: dims.height,
    estimatedModuleWidthMm: Math.round(estimatedModuleWidthMm * 1000) / 1000,
    estimatedPhysicalWidthMm: Math.round(estimatedPhysicalWidthMm * 10) / 10,
    estimatedPhysicalHeightMm: Math.round(estimatedPhysicalHeightMm * 10) / 10,
  };
  if (!quality.ok) {
    quality.warning = `Barcode module width is ${quality.estimatedModuleWidthMm}mm (recommended minimum ${MIN_MODULE_WIDTH_MM}mm) or height ${quality.estimatedPhysicalHeightMm}mm is under 15mm — this barcode may not scan reliably on a real retail scanner. Try a shorter encoded value or a larger label size.`;
  }

  return {
    dataUri: `data:image/png;base64,${png.toString('base64')}`,
    widthPx: dims.width,
    heightPx: dims.height,
    quality,
  };
}
