import { Building2, MapPin } from 'lucide-react';
import { getApiBaseURL } from '@/lib/api';

const NAVY = '#1e3a5f';

function money(value: unknown) { return `₹${((Number(value) || 0) / 100).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }
function assetUrl(value: unknown) { const raw = String(value || '').trim(); if (!raw) return ''; if (/^(https?:|data:|blob:)/.test(raw)) return raw; return `${getApiBaseURL().replace(/\/api$/, '')}/${raw.replace(/^\/+/, '')}`; }
function fullDate(value: unknown) { if (!value) return '—'; const date = new Date(`${String(value).slice(0, 10)}T00:00:00.000Z`); if (Number.isNaN(date.getTime())) return String(value); const weekdays = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat']; const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']; return `${weekdays[date.getUTCDay()]} ${months[date.getUTCMonth()]} ${String(date.getUTCDate()).padStart(2,'0')} ${date.getUTCFullYear()} 00:00:00 GMT+0000 (Coordinated Universal Time)`; }
function clauses(value: unknown) { return String(value || '').split(/\r?\n/).map((line) => line.trim().replace(/^\d+[.)]\s*/, '')).filter(Boolean); }

export default function SaleOrderDocument({ order, items, company }: { order: Record<string, any>; items: Array<Record<string, any>>; company: Record<string, any> }) {
  const logo = assetUrl(company.logo_url);
  const signature = assetUrl(company.signature_url);
  const sellerName = company.legal_name || company.name || 'Company';
  const sellerAddress = company.registered_address || company.address || [company.city, company.state, company.pincode].filter(Boolean).join(', ');
  const sellerLocation = [company.city, company.state, 'India'].filter(Boolean).join(', ');
  const interstate = order.is_interstate === true || Number(order.igst_amount || 0) > 0;
  const computed = items.reduce((acc, item) => { const qty = Number(item.quantity_ordered ?? item.quantity) || 0; const gross = Math.round(qty * (Number(item.unit_price) || 0)); const discount = Number(item.discount_amount) || 0; const taxable = Math.max(0, gross - discount); const tax = Math.round(taxable * (Number(item.gst_rate) || 0) / 100); acc.subtotal += gross; acc.discount += discount; acc.taxable += taxable; if (interstate) acc.igst += tax; else { const half = Math.round(tax / 2); acc.cgst += half; acc.sgst += tax - half; } acc.total += taxable + tax; return acc; }, { subtotal: 0, discount: 0, taxable: 0, cgst: 0, sgst: 0, igst: 0, total: 0 });
  const buyerState = [order.party_state_code_snapshot || order.party_state_code, order.party_state_snapshot || order.party_state].filter(Boolean).join(' - ') || '—';
  const billAddress = [order.billing_address, order.billing_city, order.billing_state, order.billing_pincode, order.billing_country].filter(Boolean).join(', ');
  const shipAddress = [order.shipping_address, order.shipping_city, order.shipping_state, order.shipping_pincode, order.shipping_country].filter(Boolean).join(', ');
  const termRows = clauses(order.terms_and_conditions);
  return <div className="overflow-x-auto rounded-md border bg-slate-100 p-2 sm:p-4"><article className="relative mx-auto min-w-[760px] max-w-[920px] overflow-hidden border border-slate-300 bg-white px-8 pb-12 pt-8 text-[11px] text-slate-800 shadow-sm">
    <div className="absolute right-0 top-0 h-14 w-24" style={{ background: `linear-gradient(145deg,${NAVY} 0 55%,#8fb8d8 55% 76%,transparent 76%)` }} />
    <header className="flex items-center gap-3">{logo ? <img src={logo} alt="Company logo" className="h-14 w-14 rounded-full border-2 object-contain p-1" style={{ borderColor: NAVY }} /> : <Building2 className="h-12 w-12" style={{ color: NAVY }} />}<div><h2 className="font-serif text-2xl font-bold" style={{ color: NAVY }}>{sellerName}</h2>{company.document_tagline && <p className="italic text-slate-500">{company.document_tagline}</p>}</div></header>
    <section className="my-4 grid grid-cols-[1fr_350px] items-center gap-6"><div><div className="flex items-start gap-3"><span className="grid h-7 w-7 place-items-center text-white" style={{ background: NAVY }}>≡</span><div><h1 className="text-2xl font-extrabold tracking-widest" style={{ color: NAVY }}>SALES ORDER</h1><p className="italic text-slate-500">Confirming Your Order, Powering Your Business</p></div></div><div className="mt-3 text-slate-600">{company.phone && <p>Phone no.: <b>{company.phone}</b></p>}{company.email && <p>Email: <b>{company.email}</b></p>}</div></div><div className="border border-slate-400 bg-slate-50">{[['Order No.', order.so_number || 'Auto-generated'], ['Order Date', fullDate(order.so_date)], ['Expected Delivery', fullDate(order.expected_delivery_date)]].map(([label,value]) => <div key={label} className="grid grid-cols-[125px_1fr] border-b border-slate-300 px-2 py-1.5 last:border-0"><span className="text-slate-500">{label}</span><strong className="text-right text-[10px]">{value}</strong></div>)}</div></section>
    <div className="mb-3 h-px" style={{ background: NAVY }} />
    <section className="grid grid-cols-2 gap-3"><Card title="Seller (Company Details)" name={sellerName} rows={[['Phone',company.phone || '—'],['Email',company.email || '—'],['Address',sellerAddress || '—']]} /><Card title="Buyer (Customer Details)" name={order.party_name_snapshot || order.party_name || 'Customer'} rows={[['Location',order.party_address_snapshot || order.party_address || '—'],['Phone',order.party_phone_snapshot || order.party_phone || '—'],['GSTIN',order.party_gstin_snapshot || order.party_gstin || 'URP'],['State',buyerState]]} /></section>
    <section className="mt-3 grid grid-cols-2 gap-3"><Address title="Billing Address" name={order.billing_recipient_name || order.party_name_snapshot} value={billAddress} /><Address title="Shipping Address" name={order.shipping_recipient_name || order.party_name_snapshot} value={shipAddress} /></section>
    <div className="mt-3 overflow-x-auto"><table className="w-full table-fixed border-collapse"><colgroup><col className="w-[5%]"/><col className="w-[29%]"/><col className="w-[10%]"/><col className="w-[8%]"/><col className="w-[12%]"/><col className="w-[11%]"/><col className="w-[9%]"/><col className="w-[16%]"/></colgroup><thead className="text-white" style={{ background: NAVY }}><tr>{['#','Item','HSN','Qty','Rate','Disc','GST','Total'].map((label) => <th key={label} className="border border-slate-400 p-2 text-left text-[10px] uppercase">{label}</th>)}</tr></thead><tbody>{items.map((item,index) => { const qty=Number(item.quantity_ordered ?? item.quantity)||0; const taxable=Math.max(0,Math.round(qty*(Number(item.unit_price)||0))-(Number(item.discount_amount)||0)); const total=Number(item.total_amount)||taxable+Math.round(taxable*(Number(item.gst_rate)||0)/100); return <tr key={item.id || index} className="even:bg-slate-50"><td className="border border-slate-400 p-2 text-center">{index+1}</td><td className="border border-slate-400 p-2"><strong>{item.item_name || item.name || 'Item'}</strong>{(item.item_description || item.description) && <p className="mt-1 text-[10px] text-slate-500">{item.item_description || item.description}</p>}</td><td className="border border-slate-400 p-2 text-center font-mono">{item.hsn_code || '—'}</td><td className="border border-slate-400 p-2 text-right">{qty.toLocaleString('en-IN')}</td><td className="border border-slate-400 p-2 text-right">{money(item.unit_price)}</td><td className="border border-slate-400 p-2 text-right">{money(item.discount_amount)}</td><td className="border border-slate-400 p-2 text-right">{Number(item.gst_rate)||0}%</td><td className="border border-slate-400 p-2 text-right font-bold">{money(total)}</td></tr>;})}</tbody></table></div>
    <div className="mt-3 flex justify-end"><div className="w-[320px] border border-slate-400 bg-slate-50"><Total label="Subtotal" value={money(order.subtotal_amount || computed.subtotal)} /><Total label="Discount" value={money(order.discount_amount || computed.discount)} /><Total label="Taxable Amount" value={money(order.taxable_amount || computed.taxable)} />{interstate ? <Total label="IGST" value={money(order.igst_amount || computed.igst)} /> : <><Total label="CGST" value={money(order.cgst_amount || computed.cgst)} /><Total label="SGST" value={money(order.sgst_amount || computed.sgst)} /></>}<div className="flex justify-between px-3 py-2 text-sm font-extrabold text-white" style={{ background:NAVY }}><span>Grand Total</span><span>{money(order.total_amount || computed.total)}</span></div></div></div>
    <section className="mt-3 grid grid-cols-3 border border-slate-400"><Footer label="Payment Terms" value={order.payment_terms}/><Footer label="Delivery Terms" value={order.delivery_terms}/><Footer label="Customer Notes" value={order.customer_notes || order.notes} last/></section>
    <section className="grid min-h-[120px] grid-cols-[1fr_235px] border-x border-b border-slate-400"><div className="p-3"><p className="mb-2 text-[10px] font-extrabold uppercase tracking-wider" style={{color:NAVY}}>Terms &amp; Conditions</p>{termRows.length ? <ol className="list-decimal space-y-1 pl-5">{termRows.map((term,index)=><li key={index}>{term}</li>)}</ol> : '—'}</div><div className="flex flex-col items-center border-l border-slate-400 p-3 text-center"><strong>For {sellerName}</strong>{signature ? <img src={signature} alt="Authorised signature" className="my-auto max-h-12 max-w-32 object-contain"/> : <div className="h-12"/>}<div className="w-36 border-t border-slate-500 pt-1">Authorised Signatory</div></div></section>
    <section className="mt-4 grid grid-cols-[1fr_310px]"><div className="flex items-center gap-2 border-t border-slate-400 px-2 py-2 text-slate-600"><MapPin className="h-3.5 w-3.5"/>{sellerLocation || 'India'}</div><div className="py-2 text-center font-extrabold text-white" style={{background:NAVY}}>Thank you for your business!</div></section><div className="absolute bottom-0 right-0 h-7 w-24" style={{background:`linear-gradient(145deg,transparent 0 25%,#8fb8d8 25% 52%,${NAVY} 52%)`}}/>
  </article></div>;
}

function Card({title,name,rows}:{title:string;name:string;rows:Array<[string,string]>}){return <article className="min-h-28 border border-slate-400"><div className="px-2.5 py-1.5 text-[10px] font-extrabold uppercase tracking-wider" style={{color:NAVY,background:'#e9eff6'}}>{title}</div><div className="space-y-1 p-2.5"><p className="text-sm font-extrabold">{name}</p>{rows.map(([label,value])=><p key={label} className="grid grid-cols-[62px_1fr] gap-1.5"><span className="text-slate-500">{label}</span><strong className="font-medium">{value}</strong></p>)}</div></article>}
function Address({title,name,value}:{title:string;name?:string;value:string}){return <article className="min-h-20 border border-slate-400"><div className="px-2.5 py-1.5 text-[10px] font-extrabold uppercase" style={{color:NAVY,background:'#e9eff6'}}>{title}</div><div className="p-2.5"><strong>{name || 'Customer'}</strong><p className="mt-1 text-slate-600">{value || '—'}</p></div></article>}
function Total({label,value}:{label:string;value:string}){return <div className="flex justify-between border-b border-slate-300 px-3 py-1.5"><span>{label}</span><strong>{value}</strong></div>}
function Footer({label,value,last=false}:{label:string;value?:string;last?:boolean}){return <div className={`min-h-[72px] p-2.5 ${last?'':'border-r border-slate-400'}`}><p className="mb-1.5 text-[10px] font-extrabold uppercase" style={{color:NAVY}}>{label}</p><p className="whitespace-pre-line text-slate-700">{value || '—'}</p></div>}
